app.controller('NuArtistiqueController',['$scope',($scope=>{
    $scope.ubicacion='#!/nuArtistique';
    $scope.arregloFotos=[
        {
            url:'img/nuartistique/imgFrany100.jpg'
        },
        {
            url:'img/nuartistique/imgFrany102.jpg'
        },
        {
            url:'img/nuartistique/imgFrany103.jpg'
        },
        {
            url:'img/nuartistique/imgFrany104.jpg'
        },
        {
            url:'img/nuartistique/imgFrany105.jpg'
        },
        {
            url:'img/nuartistique/imgFrany106.jpg'
        },
        {
            url:'img/nuartistique/imgFrany107.jpg'
        },
        {
            url:'img/nuartistique/imgFrany108.jpg'
        },
        {
            url:'img/nuartistique/imgFrany109.jpg'
        },
        {
            url:'img/nuartistique/imgFrany110.jpg'
        },
        {
            url:'img/nuartistique/imgFrany111.jpg'
        },
        {
            url:'img/nuartistique/imgFrany112.jpg'
        },
        {
            url:'img/nuartistique/imgFrany113.JPG'
        }
    ]
})])